### PR TITLE
Fix overflow in `kqueue` backend

### LINKED ISSUE #111: [kqueue] More than 256 Kevents per tick causes OOB
If there are more than 256 events to unpack per tick, because of the hard-coded 256 `Kevent`s, an out of bounds crash happens at https://github.com/mitchellh/libxev/blob/43c7e4b3308f359e5b758db2d824d7c447f4ed3f/src/backend/kqueue.zig#L427

I'm not sure increasing the limit is worthwhile, I was thinking of just letting the loop run through another tick.

I found the problem using `xev.Async`.

### PR DESCRIPTION
**Pull request by Corendos**
Closes #111

@mitchellh I managed to write a test to avoid regressions but I'm not sure it's deterministic, should I still add it?

### CODE REVIEW

**Comment by Corendos** [comment]
While discussing with @steeve and re-reading the issue, I think it's better to add more context. There are basically two ways we can solve that.

### 1. Cap the amount of completion executed per tick

This is simply breaking from the loop as I did in this PR.

One issue with that is that, if we are in `loop.run(.once)`, we will potentially "miss" completions because we are capped to 256 completions in one tick. We will thus give back control to the user and the remaining completions will be handled in the next tick.

### 2. Drain all the completions in one tick

For that, we need to add another loop around the `while (self.completions.pop()) |c| { ... }` block, so that we handle all the completions that are ready.

One issue with this solution is that it can end up needing multiple call to `kevent_syscall` and it kind of feels weird with respect to the `.once`


-----

So, in the end, that's why I went for the first solution, but I can get that it's not what you would expect @mitchellh. Let me know what you feel is best, and I'll make it work 😁

**Comment by steeve** [comment]
Gentle ping @mitchellh

**Comment by mitchellh** [comment]
Apologies, I just got our tests passing again. Let me take a look at this now :)

**Comment by mitchellh** [comment]
Alright, this looks good, at least to start. I think the caveat that `once` may not complete everything is reasonable.

**Pull request merged**
