### PR TITLE
io_uring: cancellation support

### PR DESCRIPTION
**Pull request by Corendos**
# Description

Adds support for cancellation in the `io_uring` backend.

# Note to reviewers

I didn't exactly know what were your expectation @mitchellh so I went for the naive solution as a first shot. It doesn't try to be smart and delegate the verification of cancellation validity to `io_uring`. I still tried to be somewhat close to what was done for the timers.

All `Completion` that can be canceled have a new error called, well, `Canceled` :grin:

Let me know if you had something else in mind, I'll work on it so that it matches your vision.

Cheers ! :grin:

### CODE REVIEW

**Comment by mitchellh** [comment]
On first glance this looks good, and tests pass! Funny enough, it looks like io_uring was the only backend that didn't support generic cancellation, so this makes it so all of them do now (I think). I'm going to let this sit for a second and come back and review it. Thank you!

**Comment by Corendos** [comment]
> I'm going to let this sit for a second and come back and review it

Sounds good, in the meantime I'll use it on my own projects to see if that's actually usable :grin:

**Comment by mitchellh** [comment]
That'd be great if you can let me know how it feels since this isn't a feature I'm using today!

**Comment by Corendos** [comment]
Actually, I didn't have much time to test it thoroughly but the few tests I did seemed to show that it was not obviously broken.

In any case, I'll do the followup if something smells fishy in the future.

Thank you for the merge !

**Pull request merged**
